include: package:pedantic/analysis_options.yaml
# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.

analyzer:
#   exclude:
#     - path/to/excluded/files/**
