name: brainfuck
description: A sample command-line Brainfuck interpreter.
version: 0.1.3
homepage: https://github.com/zonble/brainfuck_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  brainfuck:

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.4
