name: brainfuck
description: A sample command-line Brainfuck interpreter.
version: 0.1.1
homepage: https://github.com/zonble/brainfuck_dart
author: zonble <zonble@gmail.com>

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'

executables:
  brainfuck:

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.4
